version: '3.5'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es:/usr/share/elasticsearch/data
    networks: 
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601
    volumes:
      - "./kibana/config:/usr/share/kibana/config/kibana.yml"
    networks: 
      - elastic
    depends_on:
      - elasticsearch

volumes:
  es:
    driver: local
networks:
  elastic:
    driver: bridge
