apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing.fullname" . }}-worker
  labels:
    {{- include "billing-worker.labels" . | nindent 4 }}
  annotations:
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
spec:
  replicas: {{ default 2 .Values.autoscaling.worker.min }}
  selector:
    matchLabels:
      {{- include "billing-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "billing-worker.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "billing.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "api", "queue:consume", "-m" ]
          ports:
            - name: metrics
              containerPort: 9800
              protocol: TCP
          env:
{{ tpl ($.Files.GetOne "config/parameters.yaml") $ | indent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
